algoritmo "semnome"
// Função :
// Autor :
// Data : 10/03/2022
// Seção de Declarações 
var
 vendedor : caractere
 salario, soma, carros, valorVendas , loja, anna : real
inicio
ESCREVA ("Nome Vendedor: ")
LEIA (vendedor)
escreva ("Número de Carros Vendidos: ")
LEIA (carros)
ESCREVA ("Total de Vendas da loja: R$ ")
leia (loja)
anna<- (loja*0.05)
soma<- (50*carros+500 + anna)
ESCREVA ("O salário total do vendedor é de: R$ ", soma)


fimalgoritmo
